In [1]:
#importing major libraries
import numpy as np
import pandas as pd
import pandas as pd
import nltk
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.model_selection import train_test_split
from nltk import sent_tokenize, word_tokenize
from bs4 import BeautifulSoup

In [2]:
df1 = pd.read_csv('Train_nlp.csv')
df2 = pd.read_csv('Test_nlp.csv')

In [3]:
df1.head()

uniq_id  \
0  7f890f73298badd692c39c3801ef1d28   
1  83e55a2edb6c13dfc1c46d1577321b2e   
2  4bfaaf6558582a0f337ad59fcd51fcf7   
3  4e6702cb7fe9278f16dedc39a8808c72   
4  f505611d18b0ae98258896ae1b0f14c8   

                                        product_name    manufacturer   price  \
0             Batman - Role Play - Cowl and Batarang          Mattel  £14.99   
1  Doctor Who 12-inch 50th Anniversary Collector ...          Dr Who     NaN   
2           Melissa & Doug Sticker Collection - Pink  Melissa & Doug   £4.76   
3                       Rock and Roll Cards, 30 Team    ClubKing Ltd   £4.49   
4                 Crayola 16 Pipsqueak Glitter Glues         Crayola   £5.99   

  number_available_in_stock number_of_reviews  number_of_answered_questions  \
0                       NaN                 4                           1.0   
1                     3 new                73                           NaN   
2                    15 new                47                           1.0   
3                     2 new                 2                           1.0   
4                     9 new                10                           1.0   

                    amazon_category_and_sub_category  \
0     Figures & Playsets > Science Fiction & Fantasy   
1     Figures & Playsets > Science Fiction & Fantasy   
2                   Arts & Crafts > Paper & Stickers   
3  Hobbies > Trading Cards & Accessories > Packs ...   
4                      Characters & Brands > Crayola   

          customers_who_bought_this_item_also_bought  \
0  http://www.amazon.co.uk/Rubies-Costume-Co-Flas...   
1  http://www.amazon.co.uk/Doctor-Who-Classic-Dal...   
2  http://www.amazon.co.uk/Melissa-Doug-Sticker-C...   
3  http://www.amazon.co.uk/ClubKing-Ltd-Football-...   
4  http://www.amazon.co.uk/Crayola-3-3542-9-Glitt...   

                                         description  \
0  When kids aspire to be like Batman, it's easy ...   
1  Product Description This ultimate Doctor Who c...   
2  Product Description Cute couture, adorable ani...   
3  1 Pack of 25 Football Cards, 30 rockstars on e...   
4  Product Description 16 Pipsqueak washable glit...   

                                 product_information  \
0  Technical Details Item Weight113 g Product Dim...   
1  Technical Details Item Weight1.4 Kg Product Di...   
2  Technical Details Item Weight299 g Product Dim...   
3  Technical Details Item Weight100 g Product Dim...   
4  Technical Details Item Weight186 g Product Dim...   

                                 product_description  \
0  When kids aspire to be like Batman, it's easy ...   
1  Product Description This ultimate Doctor Who c...   
2  Product Description Cute couture, adorable ani...   
3  1 Pack of 25 Football Cards, 30 rockstars on e...   
4  Product Description 16 Pipsqueak washable glit...   

         items_customers_buy_after_viewing_this_item  \
0  http://www.amazon.co.uk/Rubies-Costume-Co-Flas...   
1  http://www.amazon.co.uk/Dr-Who-Dalek-Projectio...   
2  http://www.amazon.co.uk/Melissa-Doug-Habitats-...   
3  http://www.amazon.co.uk/ClubKing-Ltd-Football-...   
4  http://www.amazon.co.uk/Crayola-3-3542-9-Glitt...   

                      customer_questions_and_answers  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  how many cards in a pack it dosn't say..?? // ...   
4                                                NaN   

                                    customer_reviews  \
0  Item was broken // 3.0 // 2 April 2014 // By\n...   
1  A wonderful collectors piece // 5.0 // 31 Aug....   
2  Great sticker collection // 5.0 // 19 Jun. 201...   
3  Rock and roll cards // 5.0 // 28 July 2013 // ...   
4  Little fingers big imagination // 5.0 // 4 Mar...   

                                             sellers  average_review_rating  
0  {"seller"=>{"Seller_name_1"=>"a1 Toys", "Selle...           

In [4]:
df2.head()

uniq_id  \
0  90093bd02c6d5ce6d6c8f2e2af411fc1   
1  8dec13104fd4d1ad3ad5d9ff2af9ca0b   
2  0fcde78856668c1563f54650b17620e7   
3  69a9becbd60381a4eb7cdafe30761ee4   
4  18bc8b988f43f352b946a253642e1c6e   

                                        product_name  \
0                      Dolls House Miniature Cats x2   
1  Disney Princess T7561 Tangled Rapunzel's Gondo...   
2                           My Pirate Party Music CD   
3  1ST BIRTHDAY BANNER GIRL (BGC HOLOGRAPHIC) 9FT...   
4   Beavis and Butt-Head Great Cornholio Bobble Head   

                    manufacturer   price number_available_in_stock  \
0                      Heidi Ott  £12.00                       NaN   
1                Disney Princess     NaN                     5 new   
2                        Unknown   £4.99                    1 used   
3  Every-occasion-party-supplies   £1.49                     5 new   
4           Beavis And Butt-Head  £84.43                       NaN   

   number_of_reviews  number_of_answered_questions  \
0                  1                           1.0   
1                 15                           4.0   
2                  6                           1.0   
3                 22                           1.0   
4                  1                           1.0   

                    amazon_category_and_sub_category  \
0  Dolls & Accessories > Dolls' House Dolls & Acc...   
1                Characters & Brands > Disney > Toys   
2                       Figures & Playsets > Pirates   
3  Party Supplies > Banners, Stickers & Confetti ...   
4  Hobbies > Collectible Figures & Memorabilia > ...   

          customers_who_bought_this_item_also_bought  \
0                                                NaN   
1  http://www.amazon.co.uk/Disney-Princess-Y0942-...   
2  http://www.amazon.co.uk/Pirate-Pencils-Childre...   
3  http://www.amazon.co.uk/1ST-BIRTHDAY-GIRL-PINK...   
4                                                NaN   

                                         description  \
0  A pair of dolls house miniature cats. This 1/1...   
1  Product Description Relive the romantic moment...   
2  Set the atmosphere for your Pirate themed part...   
3                                          12ft long   
4  From the Beavis and Butt-Head TV series comes ...   

                                 product_information  \
0  Technical Details Item Weight5 g Product Dimen...   
1  Technical Details Item Weight907 g Product Dim...   
2  Technical Details Manufacturer recommended age...   
3  Technical Details Manufacturer recommended age...   
4  Technical Details Item Weight159 g Product Dim...   

                                 product_description  \
0  A pair of dolls house miniature cats. This 1/1...   
1  Product Description Relive the romantic moment...   
2  Set the atmosphere for your Pirate themed part...   
3                                          12ft long   
4  From the Beavis and Butt-Head TV series comes ...   

         items_customers_buy_after_viewing_this_item  \
0                                                NaN   
1  http://www.amazon.co.uk/Disney-Princess-Y0942-...   
2  http://www.amazon.co.uk/Jake-And-The-Neverland...   
3  http://www.amazon.co.uk/12ft-Foil-Ladybird-Bir...   
4                                                NaN   

  customer_questions_and_answers  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   

                                    customer_reviews  \
0  Dolls house miniatures // 5.0 // 9 Jan. 2013 /...   
1  Tangled // 4.0 // 16 May 2011 // By\n    \n   ...   
2  Okay but that's all // 1.0 // 11 July 2011 // ...   
3  Good quality but take down carefully as the fo...   
4  hilarious // 5.0 // 11 Dec. 2013 // By\n    \n...   

                                             sellers  
0  {"seller"=>{"Seller_name_1"=>"1 12 Dollshouses...  
1  {"seller"=>[{"Seller_

In [5]:
df1.manufacturer.value_counts()

Oxford Diecast                 126
LEGO                           119
Disney                         118
Playmobil                       95
Mattel                          93
                              ... 
Ganz USA LLC                     1
Glitter Tattoo Starter Kits      1
Noris                            1
Ever After High                  1
Puzzler Media Ltd                1
Name: manufacturer, Length: 2254, dtype: int64

In [6]:
df1.average_review_rating.value_counts() #checking the frequency of each review point

5.0    3870
4.0     999
4.5     538
4.8     425
4.7     389
4.3     299
4.6     282
4.4     234
4.9     173
4.2     159
4.1     106
3.9       3
3.3       2
3.6       2
3.5       2
3.7       2
3.0       1
Name: average_review_rating, dtype: int64

In [9]:
#checking for null values
df1.isna().sum()

uniq_id                                           0
product_name                                      0
manufacturer                                      5
price                                          1069
number_available_in_stock                      1899
number_of_reviews                                 0
number_of_answered_questions                    577
amazon_category_and_sub_category                486
customers_who_bought_this_item_also_bought      821
description                                     473
product_information                              45
product_description                             473
items_customers_buy_after_viewing_this_item    2307
customer_questions_and_answers                 6817
customer_reviews                                  3
sellers                                        2314
average_review_rating                             0
dtype: int64

In [10]:
df2.isna().sum()

uniq_id                                           0
product_name                                      0
manufacturer                                      2
price                                           363
number_available_in_stock                       598
number_of_reviews                                 0
number_of_answered_questions                    187
amazon_category_and_sub_category                198
customers_who_bought_this_item_also_bought      241
description                                     174
product_information                              13
product_description                             174
items_customers_buy_after_viewing_this_item     751
customer_questions_and_answers                 2252
customer_reviews                                  0
sellers                                         766
dtype: int64

In [12]:
df1.shape

(7486, 17)

In [13]:
df2.shape

(2496, 16)

In [14]:
#dropping null values from training set
df1.dropna(inplace = True)

In [16]:
df1.shape

(389, 17)

In [23]:
import re
def cleaning_data(raw_text, remove_stopwords=False, stemming=False, split_text=False ):
    
    text = BeautifulSoup(raw_text, 'lxml').get_text()  #remove html
    letters_only = re.sub("[^a-zA-Z]", " ", text)  # remove non-character
    words = letters_only.lower().split() # convert to lower case 
    
    if remove_stopwords: # remove stopword
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
        
    if stemming==True: # stemming
#         stemmer = PorterStemmer()
        stemmer = SnowballStemmer('english') 
        words = [stemmer.stem(w) for w in words]
        
    if split_text==True:  # split text
        return (words)
    
    return( " ".join(words)) 

In [19]:
#train test split, using customer reviews as the parameter to train the model
X_train, X_test, y_train, y_test = train_test_split(df1['customer_reviews'], df1['average_review_rating'],test_size=0.2, random_state=42)

In [24]:
#preprocessing text data and cleaning 
X_train_clean = []
X_test_clean = []

for d in X_train:
    X_train_clean.append(cleaning_data(d))

for d in X_test:
    X_test_clean.append(cleaning_data(d))

In [25]:
X_train_clean[5]

'five stars oct by mr r jobson on oct exactly as described and delivered very quickly five stars aug by louise on aug brilliant delivery and good quality product'

In [26]:
#count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
countVect = CountVectorizer() 
X_train_countVect = countVect.fit_transform(X_train_clean)

In [29]:
from sklearn import preprocessing
l = preprocessing.LabelEncoder()

In [31]:
y_train_lab=l.fit_transform(y_train)

In [32]:
y_train_lab

array([11, 11,  8,  9, 11, 11,  9, 10,  6,  4,  4, 10, 11,  5, 11,  2,  1,
        8,  2,  8,  8,  5,  7, 11,  8,  1, 11,  8,  4,  9,  6, 11,  8,  1,
       10,  5,  4,  9,  1,  5,  7,  3,  7,  2,  2,  7, 10,  7,  8,  6,  4,
        1, 10,  7,  0, 11,  3, 11,  7,  6,  6,  6,  9,  1, 11, 11,  3,  9,
        7,  6,  9,  9,  9,  8, 11, 11,  1, 11,  8, 11,  4,  8,  3,  2, 10,
        5, 11,  8, 11,  1, 10, 11, 11,  7, 11,  8,  5,  7,  7,  7,  7,  9,
        8,  1,  9, 11,  4,  1,  6,  4,  1,  5,  8, 10,  4,  1, 11,  5,  9,
       11, 11,  5, 11,  6,  6, 11,  2, 11,  7, 11,  2,  6, 11,  6,  4,  4,
        9,  8,  2,  6,  7,  6,  6,  2, 10,  7, 10, 10, 11,  8,  8, 11, 10,
       10,  2,  1, 11, 10, 11,  4,  6,  4,  7,  9,  3,  8, 11,  7,  7,  6,
        3, 10,  9,  1,  8, 11, 11, 11,  2, 11,  9,  8,  1,  7,  5,  8,  6,
        5,  8,  8,  3, 11, 11, 10, 11, 11, 10,  6,  3, 11,  1, 11,  4, 11,
        1,  7,  1,  1, 11,  9,  1, 10,  4,  6,  7,  6,  8,  6,  3,  1, 10,
       11,  1,  4, 10, 10

In [33]:
#applying label encoding on y_test
y_test_lab = l.fit_transform(y_test)

In [34]:
y_test_lab

array([ 4,  8,  0,  9,  8,  8,  4,  8,  5,  0, 11,  5, 10,  6,  3,  6, 11,
        4, 11, 11,  7,  4,  3,  9, 11, 11,  7,  1, 10, 11, 11,  5, 11,  3,
        6,  6, 10,  2,  4, 10,  9,  9,  9,  7, 11, 11, 10, 11,  2,  6,  4,
       11,  1, 11, 11,  4, 11, 11, 11,  3, 11, 11,  3,  9,  9,  3,  4,  9,
        9,  6, 11, 11,  5, 11,  8,  6,  1, 11], dtype=int64)

In [35]:
#Using Multinomial Classifier
mnb = MultinomialNB()
mnb.fit(X_train_countVect, y_train_lab)

MultinomialNB()

In [36]:
predictions = mnb.predict(countVect.transform(X_test_clean))

In [38]:
prediction =l.inverse_transform(predictions)

In [39]:
prediction

array([4.6, 4.6, 4.7, 4.7, 4.7, 4.6, 4.7, 4.6, 4.6, 4.6, 4.8, 4.6, 4.6,
       4.6, 4.3, 4.6, 4.7, 4.6, 5. , 4.7, 4.6, 4.6, 4.6, 4.6, 5. , 4.7,
       4.6, 4.7, 4.6, 5. , 4.6, 4.7, 4.7, 4.7, 4.6, 5. , 4.6, 4.6, 4.6,
       4.6, 4.7, 4.6, 4.6, 4.6, 4.6, 5. , 4.7, 5. , 4.8, 4.6, 4.6, 4.5,
       4.7, 5. , 4.6, 4.3, 4.6, 4.6, 4.6, 4.6, 4.6, 4.6, 4.5, 4.3, 4.3,
       4.6, 4.6, 4.6, 4.6, 4.6, 5. , 4.6, 4.6, 4.7, 4.7, 4.3, 4.6, 4.5])

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
def modelEvaluation(y_tst,pred):
    '''
    Print model evaluation to predicted result 
    '''
    print ("\nAccuracy on validation set: {:.4f}".format(np.sqrt(mean_squared_error(y_tst, pred))))

In [44]:
modelEvaluation(l.inverse_transform(y_test_lab),predictions)


Accuracy on validation set: 3.1841


In [45]:
#exploring test dataset
df2.isna().sum()

uniq_id                                           0
product_name                                      0
manufacturer                                      2
price                                           363
number_available_in_stock                       598
number_of_reviews                                 0
number_of_answered_questions                    187
amazon_category_and_sub_category                198
customers_who_bought_this_item_also_bought      241
description                                     174
product_information                              13
product_description                             174
items_customers_buy_after_viewing_this_item     751
customer_questions_and_answers                 2252
customer_reviews                                  0
sellers                                         766
dtype: int64

In [47]:
test_clean = []

for d in df2['customer_reviews']:
    test_clean .append(cleaning_data(d))

In [48]:
test_clean[10]

'so life like may by shoemaker vine voice on may very well painted and durable and so life like luke and ben just love these papo toys are of a very high quality i would recommend to anyone but were did he leave his horse it is on here can be used together with the papo horse if you like oct by bay on oct beautiful figure it is made to be mounted on the papo horse so if you choose to have the figure without the horse as i did then it comes up a little shorter than for instance the papo queen figure that we bought to go with him great toy jan by louise fenwick on jan delivery was good the product is lovely and sturdy and has a lot of detail my four year old boy loves it and i m very pleased just the job dec by amazon customer on dec whilst at hampton court my son purchased with pocket money a horse by papo and loved it so much that i decided to get him the rider a sneaky look at amazon to compare prices revealed a cheaper price hence i ordered him on the way home and it arrived a few da

In [49]:
predictions_test = mnb.predict(countVect.transform(test_clean))

In [50]:
predictions_test = l.inverse_transform(predictions_test)

In [51]:
predictions_test

array([4.8, 4.6, 4.6, ..., 5. , 4.8, 4.5])

In [52]:
#convert the predictions to dataframe
predictions_test = pd.DataFrame(predictions_test)

In [53]:
predictions_test.head()

0
0  4.8
1  4.6
2  4.6
3  4.7
4  4.7

In [54]:
predictions_test.index = pd.DataFrame(predictions_test).index
predictions_test.columns = ["prediction"]
predictions_test.to_csv("sub_NLP.csv", index = False)